import { FrameBuffer } from "./FrameBuffer";
import { Vec3 } from "./math/Vec3";
import { Vec4 } from "./math/Vec4";
import { MeshPrimitive } from "./MeshPrimitive";
import { Rasterization } from "./Rasterization";
import { Device } from "./Device";
import { Mat4 } from "./math/Mat4";
import { Quat } from "./math/Quat";
import { Texture2D } from "./Texture2D";
import { TextureCube } from "./TextureCube";
import { ShaderBlinnPhong } from "./shader/ShaderBlinnPhong";
import { ShaderSimple } from "./shader/ShaderSimple";
import { ShaderTest } from "./shader/ShaderTest";
import { ShaderSkybox } from "./shader/ShaderSkybox";
import { SceneManager } from "./engine/SceneManager";
import { SceneModelTest } from "./scene/SceneModelTest";
import { SceneBlendTest } from "./scene/SceneBlendTest";
import { SceneSkyboxTest } from "./scene/SceneSkyboxTest";
import { SceneDebug } from "./scene/SceneDebug";

let device = new Device();
let sceneManager = new SceneManager();
sceneManager.changeScene(new SceneDebug(device));
device.startLoop((dt) => sceneManager.update(dt));
// sceneManager.changeScene(new SceneBlendTest(device));
// sceneManager.changeScene(new SceneSkyboxTest(device));
